import swaggerJSDoc from 'swagger-jsdoc';
import { SwaggerDefinition } from 'swagger-jsdoc';

const HOST = process.env.HOST || 'localhost';
const PORT = Number(process.env.PORT) || 3003;

const swaggerDefinition: SwaggerDefinition = {
  openapi: '3.0.3',
  info: {
    title: 'Sistema Escolar Pinguinho API',
    version: '1.0.0',
    description:
      'Documentação da API do Sistema Escolar Pinguinho. ' +
      'A maioria das rotas exige autenticação via Bearer Token (JWT). ' +
      'Faça login em `POST /auth/login` para obter o token e clique em **Authorize**.',
  },
  servers: [
    { url: `http://${HOST}:${PORT}`, description: 'Servidor local' },
    {
      url: 'https://pinguinho-pingback.hvko68.easypanel.host',
      description: 'Servidor de produção',
    },
  ],
  tags: [
    { name: 'Auth', description: 'Autenticação e redefinição de senha' },
    { name: 'Usuários', description: 'Gestão de usuários' },
    { name: 'Tipos de Usuário', description: 'Gestão de tipos de usuário' },
    { name: 'Professores', description: 'Gestão de professores' },
    { name: 'Alunos', description: 'Gestão de alunos' },
    { name: 'Religião', description: 'Gestão de religiões' },
    { name: 'Certidão', description: 'Certidões de nascimento' },
    { name: 'Parentesco', description: 'Tipos de parentesco' },
    { name: 'Responsáveis', description: 'Responsáveis pelos alunos' },
    { name: 'Dados de Saúde', description: 'Dados de saúde dos alunos' },
    { name: 'Diagnóstico', description: 'Diagnósticos dos alunos' },
    { name: 'Ano Letivo', description: 'Anos letivos' },
    { name: 'Período Letivo', description: 'Períodos/bimestres letivos' },
    { name: 'Série', description: 'Séries escolares' },
    { name: 'Turma', description: 'Turmas' },
    { name: 'Matrícula', description: 'Matrículas de alunos' },
    { name: 'Ficha Cadastro', description: 'Ficha de cadastro completa' },
    { name: 'Disciplina', description: 'Disciplinas' },
    { name: 'Vinculação', description: 'Turma-Disciplina-Professor' },
    { name: 'Aula', description: 'Aulas' },
    { name: 'Conteúdo de Aula', description: 'Conteúdos de aula' },
    { name: 'Registro Diário', description: 'Registro diário de classe' },
    { name: 'Atividade', description: 'Atividades' },
    { name: 'Nota', description: 'Notas' },
    { name: 'Média Disciplina Bimestre', description: 'Médias por disciplina/bimestre' },
    { name: 'Frequência', description: 'Frequência dos alunos' },
    { name: 'Boletim', description: 'Boletins' },
    { name: 'Histórico Escolar', description: 'Histórico escolar' },
    { name: 'Alocação Professor', description: 'Alocação de professores' },
    { name: 'Professor-Disciplina', description: 'Habilitação professor-disciplina' },
    { name: 'Grade Horário', description: 'Grade de horários' },
    { name: 'Contato', description: 'Formulário de contato (público)' },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'Insira o token JWT obtido em POST /auth/login',
      },
    },
    responses: {
      NaoAutorizado: {
        description: 'Token ausente ou inválido',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/Erro' },
          },
        },
      },
      ProibidoPermissao: {
        description: 'Usuário sem permissão para esta operação',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/Erro' },
          },
        },
      },
      NaoEncontrado: {
        description: 'Recurso não encontrado',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/Erro' },
          },
        },
      },
      ErroValidacao: {
        description: 'Dados de entrada inválidos',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/Erro' },
          },
        },
      },
    },
    schemas: {
      Erro: {
        type: 'object',
        properties: {
          status: { type: 'string', example: 'erro' },
          mensagem: { type: 'string', example: 'Mensagem de erro' },
        },
      },
      Sucesso: {
        type: 'object',
        properties: {
          status: { type: 'string', example: 'sucesso' },
          mensagem: { type: 'string' },
          dados: { type: 'object' },
        },
      },
      LoginInput: {
        type: 'object',
        required: ['email', 'senha'],
        properties: {
          email: { type: 'string', format: 'email', example: 'admin@escola.com' },
          senha: { type: 'string', format: 'password', example: 'senha123' },
        },
      },
      LoginResposta: {
        type: 'object',
        properties: {
          status: { type: 'string', example: 'sucesso' },
          mensagem: { type: 'string', example: 'Login realizado com sucesso' },
          dados: {
            type: 'object',
            properties: {
              token: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' },
              usuario: { $ref: '#/components/schemas/Usuario' },
            },
          },
        },
      },
      RegistrarInput: {
        type: 'object',
        required: ['nome_usuario', 'email', 'senha', 'tipo_usuario_id'],
        properties: {
          nome_usuario: { type: 'string', example: 'Maria Silva' },
          email: { type: 'string', format: 'email', example: 'maria@escola.com' },
          senha: { type: 'string', format: 'password', example: 'senha123' },
          tipo_usuario_id: { type: 'string', enum: ['admin', 'secretario', 'professor'] },
        },
      },
      ForgotPasswordInput: {
        type: 'object',
        required: ['email'],
        properties: {
          email: { type: 'string', format: 'email', example: 'maria@escola.com' },
        },
      },
      VerifyResetCodeInput: {
        type: 'object',
        required: ['email', 'codigo'],
        properties: {
          email: { type: 'string', format: 'email' },
          codigo: { type: 'string', example: '123456' },
        },
      },
      ResetPasswordInput: {
        type: 'object',
        required: ['email', 'codigo', 'nova_senha'],
        properties: {
          email: { type: 'string', format: 'email' },
          codigo: { type: 'string', example: '123456' },
          nova_senha: { type: 'string', format: 'password' },
        },
      },
      Usuario: {
        type: 'object',
        properties: {
          usuario_id: { type: 'string', format: 'uuid' },
          nome_usuario: { type: 'string' },
          email: { type: 'string', format: 'email' },
          tipo_usuario_id: { type: 'string', enum: ['admin', 'secretario', 'professor'] },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      UsuarioTipo: {
        type: 'object',
        properties: {
          tipo_usuario_id: { type: 'string', format: 'uuid' },
          nome_tipo: { type: 'string', enum: ['admin', 'secretario', 'professor'] },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      Professor: {
        type: 'object',
        properties: {
          professor_id: { type: 'string', format: 'uuid' },
          usuario_id: { type: 'string', format: 'uuid' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      Aluno: {
        type: 'object',
        properties: {
          aluno_id: { type: 'string', format: 'uuid' },
          nome_aluno: { type: 'string', example: 'João' },
          sobrenome_aluno: { type: 'string', example: 'Souza' },
          data_nascimento_aluno: { type: 'string', format: 'date' },
          cpf_aluno: { type: 'string', example: '123.456.789-00' },
          rg_aluno: { type: 'string' },
          naturalidade_aluno: { type: 'string' },
          endereco_aluno: { type: 'string' },
          bairro_aluno: { type: 'string' },
          cep_aluno: { type: 'string' },
          religiao_id: { type: 'string', format: 'uuid', nullable: true },
          certidao_id: { type: 'string', format: 'uuid', nullable: true },
          foto_aluno: { type: 'string', nullable: true, description: 'Base64 ou URL' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      AlunoInput: {
        type: 'object',
        required: ['nome_aluno', 'sobrenome_aluno', 'data_nascimento_aluno', 'cpf_aluno'],
        properties: {
          nome_aluno: { type: 'string', example: 'João' },
          sobrenome_aluno: { type: 'string', example: 'Souza' },
          data_nascimento_aluno: { type: 'string', format: 'date', example: '2015-03-10' },
          cpf_aluno: { type: 'string', example: '123.456.789-00' },
          rg_aluno: { type: 'string' },
          naturalidade_aluno: { type: 'string' },
          endereco_aluno: { type: 'string' },
          bairro_aluno: { type: 'string' },
          cep_aluno: { type: 'string' },
          religiao_id: { type: 'string', format: 'uuid', nullable: true },
          certidao_id: { type: 'string', format: 'uuid', nullable: true },
          foto_aluno: { type: 'string', nullable: true },
        },
      },
      Religiao: {
        type: 'object',
        properties: {
          religiao_id: { type: 'string', format: 'uuid' },
          nome_religiao: { type: 'string', example: 'Católica' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      ReligiaoInput: {
        type: 'object',
        required: ['nome_religiao'],
        properties: { nome_religiao: { type: 'string', example: 'Católica' } },
      },
      CertidaoNascimento: {
        type: 'object',
        properties: {
          certidao_id: { type: 'string', format: 'uuid' },
          livro_certidao: { type: 'string' },
          matricula_certidao: { type: 'string' },
          termo_certidao: { type: 'string' },
          folha_certidao: { type: 'string' },
          data_expedicao_certidao: { type: 'string', format: 'date' },
          nome_cartorio_certidao: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      CertidaoInput: {
        type: 'object',
        required: ['livro_certidao', 'matricula_certidao', 'termo_certidao', 'folha_certidao'],
        properties: {
          livro_certidao: { type: 'string' },
          matricula_certidao: { type: 'string' },
          termo_certidao: { type: 'string' },
          folha_certidao: { type: 'string' },
          data_expedicao_certidao: { type: 'string', format: 'date' },
          nome_cartorio_certidao: { type: 'string' },
        },
      },
      Parentesco: {
        type: 'object',
        properties: {
          parentesco_id: { type: 'string', format: 'uuid' },
          nome_parentesco: { type: 'string', example: 'Mãe' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      ParentescoInput: {
        type: 'object',
        required: ['nome_parentesco'],
        properties: { nome_parentesco: { type: 'string', example: 'Mãe' } },
      },
      Responsavel: {
        type: 'object',
        properties: {
          responsavel_id: { type: 'string', format: 'uuid' },
          aluno_id: { type: 'string', format: 'uuid' },
          telefone_responsavel: { type: 'string' },
          nome_responsavel: { type: 'string' },
          sobrenome_responsavel: { type: 'string' },
          rg_responsavel: { type: 'string' },
          cpf_responsavel: { type: 'string' },
          grau_instrucao_responsavel: { type: 'string' },
          email_responsavel: { type: 'string', format: 'email' },
          parentesco_id: { type: 'string', format: 'uuid' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      ResponsavelInput: {
        type: 'object',
        required: ['aluno_id', 'nome_responsavel', 'cpf_responsavel', 'parentesco_id'],
        properties: {
          aluno_id: { type: 'string', format: 'uuid' },
          telefone_responsavel: { type: 'string' },
          nome_responsavel: { type: 'string' },
          sobrenome_responsavel: { type: 'string' },
          rg_responsavel: { type: 'string' },
          cpf_responsavel: { type: 'string' },
          grau_instrucao_responsavel: { type: 'string' },
          email_responsavel: { type: 'string', format: 'email' },
          parentesco_id: { type: 'string', format: 'uuid' },
        },
      },
      DadosSaude: {
        type: 'object',
        properties: {
          dados_saude_id: { type: 'string', format: 'uuid' },
          aluno_id: { type: 'string', format: 'uuid' },
          necessidades_especiais: { type: 'string' },
          vacinas_em_dia: { type: 'boolean' },
          dorme_bem: { type: 'boolean' },
          alimenta_se_bem: { type: 'boolean' },
          uso_sanitario_sozinho: { type: 'boolean' },
          restricao_alimentar: { type: 'string' },
          problema_saude: { type: 'string' },
          alergia_medicamento: { type: 'string' },
          uso_continuo_medicamento: { type: 'string' },
          alergias: { type: 'string' },
          medicacao_febre: { type: 'string' },
          medicacao_dor_cabeca: { type: 'string' },
          medicacao_dor_barriga: { type: 'string' },
          historico_convulsao: { type: 'boolean' },
          perda_esfincter_emocional: { type: 'boolean' },
          frequentou_outra_escola: { type: 'boolean' },
          tipo_parto: { type: 'string' },
          gravidez_tranquila: { type: 'boolean' },
          medicacao_gravidez: { type: 'string' },
          tem_irmaos: { type: 'boolean' },
          fonoaudiologico: { type: 'boolean' },
          psicopedagogico: { type: 'boolean' },
          neurologico: { type: 'boolean' },
          outro_tratamento: { type: 'string' },
          motivo_tratamento: { type: 'string' },
          observacoes: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      Diagnostico: {
        type: 'object',
        properties: {
          diagnostico_id: { type: 'string', format: 'uuid' },
          aluno_id: { type: 'string', format: 'uuid' },
          cegueira: { type: 'boolean' },
          baixa_visao: { type: 'boolean' },
          surdez: { type: 'boolean' },
          deficiencia_auditiva: { type: 'boolean' },
          surdocegueira: { type: 'boolean' },
          deficiencia_fisica: { type: 'boolean' },
          deficiencia_multipla: { type: 'boolean' },
          deficiencia_intelectual: { type: 'boolean' },
          sindrome_down: { type: 'boolean' },
          altas_habilidades: { type: 'boolean' },
          tea: { type: 'boolean' },
          alteracoes_processamento_auditivo: { type: 'boolean' },
          tdah: { type: 'boolean' },
          outros_diagnosticos: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      AnoLetivo: {
        type: 'object',
        properties: {
          ano_letivo_id: { type: 'string', format: 'uuid' },
          ano: { type: 'integer', example: 2026 },
          data_inicio: { type: 'string', format: 'date' },
          data_fim: { type: 'string', format: 'date' },
          ativo: { type: 'boolean' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      AnoLetivoInput: {
        type: 'object',
        required: ['ano', 'data_inicio', 'data_fim'],
        properties: {
          ano: { type: 'integer', example: 2026 },
          data_inicio: { type: 'string', format: 'date', example: '2026-02-01' },
          data_fim: { type: 'string', format: 'date', example: '2026-12-15' },
          ativo: { type: 'boolean', example: true },
        },
      },
      PeriodoLetivo: {
        type: 'object',
        properties: {
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          bimestre: { type: 'integer', example: 1 },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          data_inicio: { type: 'string', format: 'date', nullable: true },
          data_fim: { type: 'string', format: 'date', nullable: true },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      PeriodoLetivoInput: {
        type: 'object',
        required: ['bimestre', 'ano_letivo_id'],
        properties: {
          bimestre: { type: 'integer', example: 1 },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          data_inicio: { type: 'string', format: 'date', nullable: true },
          data_fim: { type: 'string', format: 'date', nullable: true },
        },
      },
      Serie: {
        type: 'object',
        properties: {
          serie_id: { type: 'string', format: 'uuid' },
          nome_serie: { type: 'string', example: '1º Ano' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      SerieInput: {
        type: 'object',
        required: ['nome_serie'],
        properties: { nome_serie: { type: 'string', example: '1º Ano' } },
      },
      Turma: {
        type: 'object',
        properties: {
          turma_id: { type: 'string', format: 'uuid' },
          serie_id: { type: 'string', format: 'uuid' },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          nome_turma: { type: 'string', example: 'A' },
          turno: { type: 'string', example: 'matutino' },
          sala: { type: 'string', example: 'Sala 5' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      TurmaInput: {
        type: 'object',
        required: ['serie_id', 'ano_letivo_id', 'nome_turma', 'turno'],
        properties: {
          serie_id: { type: 'string', format: 'uuid' },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          nome_turma: { type: 'string', example: 'A' },
          turno: { type: 'string', example: 'matutino' },
          sala: { type: 'string', example: 'Sala 5' },
        },
      },
      MatriculaAluno: {
        type: 'object',
        properties: {
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          ra: { type: 'string', example: '2026000123' },
          aluno_id: { type: 'string', format: 'uuid' },
          turma_id: { type: 'string', format: 'uuid' },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid', nullable: true },
          data_matricula: { type: 'string', format: 'date' },
          data_saida: { type: 'string', format: 'date', nullable: true },
          motivo_saida: { type: 'string', nullable: true },
          status: { type: 'string', enum: ['ativo', 'transferido', 'concluido', 'cancelado'] },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      MatriculaAlunoInput: {
        type: 'object',
        required: ['aluno_id', 'turma_id', 'ano_letivo_id'],
        properties: {
          aluno_id: { type: 'string', format: 'uuid' },
          turma_id: { type: 'string', format: 'uuid' },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid', nullable: true },
          data_matricula: { type: 'string', format: 'date' },
        },
      },
      Disciplina: {
        type: 'object',
        properties: {
          disciplina_id: { type: 'string', format: 'uuid' },
          nome_disciplina: { type: 'string', example: 'Matemática' },
          categoria: { type: 'string', enum: ['base', 'especial'] },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      DisciplinaInput: {
        type: 'object',
        required: ['nome_disciplina', 'categoria'],
        properties: {
          nome_disciplina: { type: 'string', example: 'Matemática' },
          categoria: { type: 'string', enum: ['base', 'especial'] },
        },
      },
      TurmaDisciplinaProfessor: {
        type: 'object',
        properties: {
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          turma_id: { type: 'string', format: 'uuid' },
          disciplina_id: { type: 'string', format: 'uuid' },
          professor_id: { type: 'string', format: 'uuid' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      VinculacaoInput: {
        type: 'object',
        required: ['turma_id', 'disciplina_id', 'professor_id'],
        properties: {
          turma_id: { type: 'string', format: 'uuid' },
          disciplina_id: { type: 'string', format: 'uuid' },
          professor_id: { type: 'string', format: 'uuid' },
        },
      },
      Aula: {
        type: 'object',
        properties: {
          aula_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid', nullable: true },
          data_aula: { type: 'string', format: 'date' },
          hora_inicio: { type: 'string', example: '08:00' },
          hora_fim: { type: 'string', example: '09:00' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      AulaInput: {
        type: 'object',
        required: ['turma_disciplina_professor_id', 'data_aula', 'hora_inicio', 'hora_fim'],
        properties: {
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid', nullable: true },
          data_aula: { type: 'string', format: 'date', example: '2026-03-10' },
          hora_inicio: { type: 'string', example: '08:00' },
          hora_fim: { type: 'string', example: '09:00' },
        },
      },
      ConteudoAula: {
        type: 'object',
        properties: {
          conteudo_aula_id: { type: 'string', format: 'uuid' },
          aula_id: { type: 'string', format: 'uuid', nullable: true },
          data_aula: { type: 'string', format: 'date' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          descricao: { type: 'string' },
          conteudo: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      ConteudoAulaInput: {
        type: 'object',
        required: ['data_aula', 'turma_disciplina_professor_id', 'descricao', 'conteudo'],
        properties: {
          data_aula: { type: 'string', format: 'date' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          descricao: { type: 'string' },
          conteudo: { type: 'string' },
        },
      },
      RegistroDiario: {
        type: 'object',
        properties: {
          registro_diario_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          data_aula: { type: 'string', format: 'date' },
          resumo: { type: 'string', description: 'HTML do editor rico' },
          conteudo_programatico: { type: 'string', nullable: true },
          metodologia: { type: 'string', nullable: true },
          recursos: { type: 'array', items: { type: 'string' }, nullable: true },
          observacoes: { type: 'string', nullable: true },
          fotos: { type: 'array', items: { type: 'string' }, nullable: true, description: 'Base64' },
          status: { type: 'string', enum: ['rascunho', 'concluido'] },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      RegistroDiarioInput: {
        type: 'object',
        required: ['turma_disciplina_professor_id', 'data_aula', 'resumo'],
        properties: {
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          data_aula: { type: 'string', format: 'date' },
          resumo: { type: 'string' },
          conteudo_programatico: { type: 'string', nullable: true },
          metodologia: { type: 'string', nullable: true },
          recursos: { type: 'array', items: { type: 'string' }, nullable: true },
          observacoes: { type: 'string', nullable: true },
          fotos: { type: 'array', items: { type: 'string' }, nullable: true },
          status: { type: 'string', enum: ['rascunho', 'concluido'] },
        },
      },
      Atividade: {
        type: 'object',
        properties: {
          atividade_id: { type: 'string', format: 'uuid' },
          titulo: { type: 'string' },
          descricao: { type: 'string' },
          peso: { type: 'number', example: 1 },
          vale_nota: { type: 'boolean' },
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          aula_id: { type: 'string', format: 'uuid', nullable: true },
          data_aula: { type: 'string', format: 'date', nullable: true },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      AtividadeInput: {
        type: 'object',
        required: ['titulo', 'peso', 'vale_nota', 'periodo_letivo_id', 'turma_disciplina_professor_id'],
        properties: {
          titulo: { type: 'string', example: 'Prova 1' },
          descricao: { type: 'string' },
          peso: { type: 'number', example: 1 },
          vale_nota: { type: 'boolean', example: true },
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          data_aula: { type: 'string', format: 'date', nullable: true },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
        },
      },
      Nota: {
        type: 'object',
        properties: {
          nota_id: { type: 'string', format: 'uuid' },
          atividade_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          valor: { type: 'number', example: 8.5 },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      NotaInput: {
        type: 'object',
        required: ['atividade_id', 'matricula_aluno_id', 'valor'],
        properties: {
          atividade_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          valor: { type: 'number', example: 8.5 },
        },
      },
      NotaLoteInput: {
        type: 'object',
        required: ['atividade_id', 'notas'],
        properties: {
          atividade_id: { type: 'string', format: 'uuid' },
          notas: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                matricula_aluno_id: { type: 'string', format: 'uuid' },
                valor: { type: 'number' },
              },
            },
          },
        },
      },
      MediaDisciplinaBimestre: {
        type: 'object',
        properties: {
          media_disciplina_bimestre_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          valor_media: { type: 'number', example: 7.5 },
          origem: { type: 'string', enum: ['manual', 'calculada'] },
          observacao: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      MediaDisciplinaBimestreInput: {
        type: 'object',
        required: ['matricula_aluno_id', 'turma_disciplina_professor_id', 'periodo_letivo_id', 'valor_media'],
        properties: {
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          valor_media: { type: 'number', example: 7.5 },
          origem: { type: 'string', enum: ['manual', 'calculada'] },
          observacao: { type: 'string' },
        },
      },
      Frequencia: {
        type: 'object',
        properties: {
          frequencia_id: { type: 'string', format: 'uuid' },
          aula_id: { type: 'string', format: 'uuid', nullable: true },
          data_aula: { type: 'string', format: 'date' },
          professor_id: { type: 'string', format: 'uuid' },
          turma_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          presenca: { type: 'boolean' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      FrequenciaInput: {
        type: 'object',
        required: ['data_aula', 'professor_id', 'turma_id', 'matricula_aluno_id', 'presenca'],
        properties: {
          data_aula: { type: 'string', format: 'date' },
          professor_id: { type: 'string', format: 'uuid' },
          turma_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          presenca: { type: 'boolean' },
        },
      },
      Boletim: {
        type: 'object',
        properties: {
          boletim_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          observacoes_gerais: { type: 'string', nullable: true },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      BoletimInput: {
        type: 'object',
        required: ['matricula_aluno_id', 'periodo_letivo_id'],
        properties: {
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          periodo_letivo_id: { type: 'string', format: 'uuid' },
          observacoes_gerais: { type: 'string', nullable: true },
        },
      },
      BoletimDisciplina: {
        type: 'object',
        properties: {
          boletim_disciplina_id: { type: 'string', format: 'uuid' },
          boletim_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          media_bimestre: { type: 'number' },
          faltas_bimestre: { type: 'integer' },
          observacoes_disciplina: { type: 'string', nullable: true },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      BoletimDisciplinaInput: {
        type: 'object',
        required: ['boletim_id', 'turma_disciplina_professor_id', 'media_bimestre', 'faltas_bimestre'],
        properties: {
          boletim_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          media_bimestre: { type: 'number' },
          faltas_bimestre: { type: 'integer' },
          observacoes_disciplina: { type: 'string', nullable: true },
        },
      },
      HistoricoEscolar: {
        type: 'object',
        properties: {
          historico_escolar_id: { type: 'string', format: 'uuid' },
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          situacao_final: {
            type: 'string',
            enum: ['aprovado', 'reprovado', 'aprovado_conselho', 'transferido', 'em_andamento'],
          },
          observacoes_finais: { type: 'string', nullable: true },
          data_conclusao: { type: 'string', format: 'date', nullable: true },
          media_geral_anual: { type: 'number', nullable: true },
          total_disciplinas_cursadas: { type: 'integer' },
          disciplinas_aprovadas: { type: 'integer' },
          disciplinas_reprovadas: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      HistoricoEscolarInput: {
        type: 'object',
        required: ['matricula_aluno_id', 'ano_letivo_id'],
        properties: {
          matricula_aluno_id: { type: 'string', format: 'uuid' },
          ano_letivo_id: { type: 'string', format: 'uuid' },
          situacao_final: {
            type: 'string',
            enum: ['aprovado', 'reprovado', 'aprovado_conselho', 'transferido', 'em_andamento'],
          },
          observacoes_finais: { type: 'string', nullable: true },
        },
      },
      GradeHorarioProfessor: {
        type: 'object',
        properties: {
          grade_horario_id: { type: 'string', format: 'uuid' },
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          dia_semana: { type: 'integer', description: '0=Domingo ... 6=Sábado', example: 1 },
          hora_inicio: { type: 'string', example: '08:00' },
          hora_fim: { type: 'string', example: '09:00' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      GradeHorarioInput: {
        type: 'object',
        required: ['turma_disciplina_professor_id', 'dia_semana', 'hora_inicio', 'hora_fim'],
        properties: {
          turma_disciplina_professor_id: { type: 'string', format: 'uuid' },
          dia_semana: { type: 'integer', example: 1 },
          hora_inicio: { type: 'string', example: '08:00' },
          hora_fim: { type: 'string', example: '09:00' },
        },
      },
      ContatoInput: {
        type: 'object',
        required: ['nome', 'email', 'mensagem'],
        properties: {
          nome: { type: 'string' },
          email: { type: 'string', format: 'email' },
          mensagem: { type: 'string' },
        },
      },
    },
  },
  security: [{ bearerAuth: [] }],
};

const options: swaggerJSDoc.Options = {
  swaggerDefinition,
  apis: ['./src/routes/*.ts', './dist/routes/*.js', './build/routes/*.js'],
};

export const swaggerSpec = swaggerJSDoc(options);
